language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
  - php: nightly
  fast_finish: true

before_script:
  - cp .env.travis .env
  - composer install --prefer-source --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit
