env:
  global:
    secure: JnTZZoRGptTavKbFkz/1XAvztL9HCZcQI0ImQ0V6Dp9ELoQK4LHOg8gwlhXFrbbDDisqVQCuBLY2iQUutkeO4ReOE1Ve46lTb7h1rHZTWptpSqKI1hhveSdRMZCOmGmKUZ7U57YRKObdH/4HNwrPWeYAQC2CQZHWvLQ0Wrn9sDI=

language: php

php:
- 5.6
- 7.0

matrix:
  allow_failures:
  - php: 5.6
  fast_finish: true

before_script:
- bash bin/init.sh testing

script:
- vendor/bin/phpunit

after_success:
  - eval $TEST_SCRIPT
