language: php

php:
  - 7.1

before_script:
  - bash bin/init.sh testing

script:
  - vendor/bin/phpunit --coverage-clover storage/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls -v
