env:
  global:
    secure: RaWN5naUxAviILksYeFbqZxbrvp59CBmRviuxZNCvnPAKrWs0vC8yLKRAUPSIgabfbJKQUlEGsBGLb3Cq3113ObzwjcspfbzmrE90wUHEBEbxidyIMVtexj9n+vmfneIWANPIDjlHTK+VZ0g5t4pBpqMRlchZYV6p+WRTYSPEfk=

language: php

php:
- 5.6
- 7.0

matrix:
  allow_failures:
  - php: 5.6
  fast_finish: true

before_script:
- bash bin/init.sh testing

script:
- vendor/bin/phpunit

after_success:
  eval $TEST_SCRIPT
