language: php

php:
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
  - php: 5.6
  - php: nightly
  fast_finish: true

before_script:
  - bash bin/init.sh testing

script:
  - vendor/bin/phpunit
