version: '2'
services:
    web:
        build: .docker/web
        environment:
            - VIRTUAL_HOST=opendominion.docker
            - VIRTUAL_PORT=80
            - HTTPS_METHOD=noredirect
        links:
            - php
        volumes:
            - .:/app

    php:
        build: .docker/php
        links:
            - db
        volumes:
            - .:/app

    db:
        image: mariadb:latest
        environment:
          - MYSQL_ROOT_PASSWORD=supersecurepassword
          - MYSQL_DATABASE=opendominion
          - MYSQL_USER=opendominion
          - MYSQL_PASSWORD=opendominion
        ports:
          - 3306:3306